import {Dimensions, StyleSheet} from 'react-native';
import Theme from '../../../theme/Theme';

const {width} = Dimensions.get('window');

const styles = StyleSheet.create({
  viewMainContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: Theme.colors.bgColor1,
  },
  container: {
    flex: 1,
    backgroundColor: Theme.colors.bgColor2,
  },
  appImage: {
    position: 'absolute',
    height: width + Theme.responsiveSize.size48,
    width: width,
  },
  viewTop: {
    paddingTop: Theme.responsiveSize.size70,
    paddingBottom: Theme.responsiveSize.size35,
  },
  textTitle: {
    textAlign: 'center',
    fontSize: Theme.responsiveSize.size32,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor2,
  },
  viewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Theme.responsiveSize.size08,
  },
  textSubTitle: {
    opacity: 0.7,
    fontSize: Theme.responsiveSize.size16,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor10,
    marginHorizontal: Theme.responsiveSize.size04,
    letterSpacing: -0.4,
  },
  infoIcon: {
    height: Theme.responsiveSize.size22,
    width: Theme.responsiveSize.size22,
    marginHorizontal: Theme.responsiveSize.size04,
  },
  viewMain: {},
  viewFeatureCard: {
    backgroundColor: Theme.colors.bgColor4,
    borderRadius: Theme.responsiveSize.size38,
    padding: Theme.responsiveSize.size22,
    marginHorizontal: Theme.responsiveSize.size20,
  },
  textFeatureTitle: {
    textAlign: 'center',
    fontSize: Theme.responsiveSize.size22,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor2,
    letterSpacing: -0.8,
    lineHeight: Theme.responsiveSize.size34,
  },
  textFeatureSubTitle: {
    textAlign: 'center',
    fontSize: Theme.responsiveSize.size14,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor10,
    letterSpacing: -0.3,
    lineHeight: Theme.responsiveSize.size22,
    paddingVertical: Theme.responsiveSize.size04,
  },
  textYourGoals: {
    letterSpacing: -0.8,
    color: Theme.colors.textColor1,
    fontFamily: Theme.fonts.fontSansBold,
    fontSize: Theme.responsiveSize.size22,
    marginHorizontal: Theme.responsiveSize.size20,
  },
  viewYourGoals: {
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size38,
    paddingHorizontal: Theme.responsiveSize.size26,
    paddingVertical: Theme.responsiveSize.size30,
    marginHorizontal: Theme.responsiveSize.size20,
    marginTop: Theme.responsiveSize.size08,
    marginBottom: Theme.responsiveSize.size24,
  },
  textNewHomeGoal: {
    color: Theme.colors.textColor13,
    fontFamily: Theme.fonts.fontSansMedium,
    fontSize: Theme.responsiveSize.size16,
  },
  textYourGoalsPrice: {
    color: Theme.colors.textColor1,
    fontFamily: Theme.fonts.fontSansBold,
    fontSize: Theme.responsiveSize.size34,
    marginVertical: Theme.responsiveSize.size08,
  },
  textYourGoalsSubTitle: {
    color: Theme.colors.textColor12,
    fontFamily: Theme.fonts.fontSansMedium,
    fontSize: Theme.responsiveSize.size16,
  },
  textYourGoalsDeposite: {
    color: Theme.colors.textColor12,
    fontFamily: Theme.fonts.fontSansMedium,
    fontSize: Theme.responsiveSize.size12,
    lineHeight: Theme.responsiveSize.size22,
  },
  viewProgress: {
    backgroundColor: Theme.colors.bgColor19,
    borderRadius: Theme.responsiveSize.size15,
    marginTop: Theme.responsiveSize.size10,
  },
  viewInnerProgress: {
    backgroundColor: Theme.colors.bgColor4,
    height: Theme.responsiveSize.size14,
    width: Theme.responsiveSize.size14,
    borderTopLeftRadius: Theme.responsiveSize.size15,
    borderBottomLeftRadius: Theme.responsiveSize.size15,
  },
  textYourGoalsDate: {
    color: Theme.colors.textColor1,
    fontFamily: Theme.fonts.fontSansBold,
    fontSize: Theme.responsiveSize.size12,
    lineHeight: Theme.responsiveSize.size22,
  },
  viewPlus: {
    backgroundColor: Theme.colors.textColor11,
    padding: Theme.responsiveSize.size18,
    borderRadius: Theme.responsiveSize.size50,
  },
  plusIcon: {
    height: Theme.responsiveSize.size18,
    width: Theme.responsiveSize.size18,
  },
  textFeatureCommonTitle: {
    fontSize: Theme.responsiveSize.size16,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor2,
    letterSpacing: -0.4,
    marginLeft: Theme.responsiveSize.size12,
  },
  viewAccountCard: {
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size38,
    padding: Theme.responsiveSize.size22,
    marginVertical: Theme.responsiveSize.size24,
    marginHorizontal: Theme.responsiveSize.size20,
  },
  cardIcon: {
    alignSelf: 'center',
    height: Theme.responsiveSize.size100,
    width: Theme.responsiveSize.size100,
    marginTop: Theme.responsiveSize.size18,
  },
  viewInvitation: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size38,
    padding: Theme.responsiveSize.size12,
    paddingRight: Theme.responsiveSize.size26,
    marginBottom: Theme.responsiveSize.size40,
    marginHorizontal: Theme.responsiveSize.size20,
  },
  viewCircles: {
    backgroundColor: Theme.colors.bgColor10,
    borderRadius: Theme.responsiveSize.size38,
    padding: Theme.responsiveSize.size14,
  },
  circleIcon: {
    height: Theme.responsiveSize.size70,
    width: Theme.responsiveSize.size70,
  },
  textInviteTitle: {
    fontSize: Theme.responsiveSize.size18,
    fontFamily: Theme.fonts.fontSansSemiBold,
    color: Theme.colors.textColor1,
    letterSpacing: -0.4,
    lineHeight: Theme.responsiveSize.size28,
  },
  textInviteSubTitle: {
    flex: 1,
    fontSize: Theme.responsiveSize.size14,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor12,
    letterSpacing: -0.3,
    lineHeight: Theme.responsiveSize.size24,
  },
  viewEarn: {
    alignSelf: 'flex-start',
    backgroundColor: Theme.colors.bgColor11,
    borderRadius: Theme.responsiveSize.size12,
    paddingVertical: Theme.responsiveSize.size06,
    paddingHorizontal: Theme.responsiveSize.size10,
  },
  textEarn: {
    fontSize: Theme.responsiveSize.size14,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor7,
    letterSpacing: -0.3,
    lineHeight: Theme.responsiveSize.size24,
  },
  copyIcon: {
    height: Theme.responsiveSize.size22,
    width: Theme.responsiveSize.size22,
  },
  viewTotalEarned: {
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size38,
    padding: Theme.responsiveSize.size22,
    paddingHorizontal: Theme.responsiveSize.size26,
    marginVertical: Theme.responsiveSize.size24,
    marginHorizontal: Theme.responsiveSize.size20,
  },
  viewRowTotal: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textTotalEarned: {
    flex: 1,
    fontSize: Theme.responsiveSize.size16,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor1,
  },
  textDate: {
    fontSize: Theme.responsiveSize.size14,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor1,
  },
  viewChartMain: {},
  graphImage: {
    height: width / 2,
    width: width - Theme.responsiveSize.size100,
  },
  viewButton: {
    marginHorizontal: 0,
    marginTop: Theme.responsiveSize.size06,
  },
  viewRowMain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textRecentTitle: {
    flex: 1,
    fontSize: Theme.responsiveSize.size16,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor1,
  },
  textRecentSeeAll: {
    fontSize: Theme.responsiveSize.size12,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor7,
  },
  viewRecentActivity: {
    minWidth: width / 3.1,
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size22,
    padding: Theme.responsiveSize.size14,
    marginRight: Theme.responsiveSize.size08,
  },
  textRecentSubTitle: {
    fontSize: Theme.responsiveSize.size12,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor1,
    paddingTop: Theme.responsiveSize.size16,
  },
  viewRecentActivityPrice: {
    alignSelf: 'flex-start',
    backgroundColor: Theme.colors.bgColor11,
    paddingHorizontal: Theme.responsiveSize.size08,
    paddingVertical: Theme.responsiveSize.size04,
    borderRadius: Theme.responsiveSize.size10,
    marginTop: Theme.responsiveSize.size10,
  },
  textPriceRecentActivity: {
    fontSize: Theme.responsiveSize.size12,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor1,
  },
  viewRecentButton: {
    marginTop: Theme.responsiveSize.size08,
    marginBottom: Theme.responsiveSize.size22,
  },
  viewFinance: {
    minWidth: width / 2 - Theme.responsiveSize.size40,
    backgroundColor: Theme.colors.bgColor9,
    borderRadius: Theme.responsiveSize.size30,
    paddingHorizontal: Theme.responsiveSize.size14,
    paddingVertical: Theme.responsiveSize.size24,
    marginRight: Theme.responsiveSize.size08,
  },
  viewFinancePrice: {
    alignSelf: 'flex-start',
    backgroundColor: Theme.colors.bgColor11,
    paddingHorizontal: Theme.responsiveSize.size08,
    paddingVertical: Theme.responsiveSize.size04,
    borderRadius: Theme.responsiveSize.size10,
    marginBottom: Theme.responsiveSize.size10,
  },
  textPrice: {
    fontSize: Theme.responsiveSize.size12,
    fontFamily: Theme.fonts.fontSansMedium,
    color: Theme.colors.textColor7,
  },
  textTitleFinance: {
    fontSize: Theme.responsiveSize.size14,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor1,
    marginBottom: Theme.responsiveSize.size06,
  },
  textSubTitleFinance: {
    fontSize: Theme.responsiveSize.size20,
    fontFamily: Theme.fonts.fontSansBold,
    color: Theme.colors.textColor1,
  },
});

export default styles;
